// <auto-generated />
namespace AgilusFinan.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Alteraçãoprocedurepr_titulos_pendentes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alteraçãoprocedurepr_titulos_pendentes));
        
        string IMigrationMetadata.Id
        {
            get { return "201508172140386_Alteração procedure pr_titulos_pendentes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
