// <auto-generated />
namespace AgilusFinan.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class inclusao_pais : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inclusao_pais));
        
        string IMigrationMetadata.Id
        {
            get { return "201501302008356_inclusao_pais"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
