// <auto-generated />
namespace AgilusFinan.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Conta_Bancaria_Na_Empresa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Conta_Bancaria_Na_Empresa));
        
        string IMigrationMetadata.Id
        {
            get { return "201502132021138_Conta_Bancaria_Na_Empresa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
