// <auto-generated />
namespace AgilusFinan.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AumentarlimitedocampodeEmailFinanceiroemPessoa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AumentarlimitedocampodeEmailFinanceiroemPessoa));
        
        string IMigrationMetadata.Id
        {
            get { return "201611231329239_Aumentar limite do campo de E-mail Financeiro em Pessoa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
