// <auto-generated />
namespace AgilusFinan.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class definetamanhomaximoparaobservaçãoemtitulorecorrente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(definetamanhomaximoparaobservaçãoemtitulorecorrente));
        
        string IMigrationMetadata.Id
        {
            get { return "202205261558286_define tamanho maximo para observação em titulorecorrente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
