// <auto-generated />
namespace AgilusFinan.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class adicionafunçãodefaturagerada : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adicionafunçãodefaturagerada));
        
        string IMigrationMetadata.Id
        {
            get { return "202202101401551_adiciona função de fatura gerada"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
