// <auto-generated />
namespace AgilusFinan.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class adicionaurlfaturacheckoutemfaturagerada : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adicionaurlfaturacheckoutemfaturagerada));
        
        string IMigrationMetadata.Id
        {
            get { return "202410311903417_adiciona urlfaturacheckout em faturagerada"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
